config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  devise_for :logins
  resources :users
end

app/models/login.rb
class Login < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
end

app/models/user.rb
class User < ActiveRecord::Base
  validates(:title,
    presence:true)
  validates(:body,
            presence:{message:'must be entered'},
            length: {maximum: 500})
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_login!, except: [:index, :show]
  before_action(:get_user, only: [:show,:edit,:update,:destroy])
  def index
    @users=User.all
 end
  def new
    @user=User.new
 end
   def create
    @user=User.create(user_params)
    redirect_to_user_if_valid(:new, 'Your new find was just created!')
end
   def show
     get_user
 end

   def update
    get_user
    @user.update(user_params)
   redirect_to_user_if_valid(:new, "Your find has been updated.")
 end
    def destroy
      @user.destroy
  end

    private
   def user_params
    params[:user].permit(:title,:body)
  end
   def get_user
     @user=User.find(params[:id])
  end
    def redirect_to_user_if_valid(action,message)
      if @user.valid?
        redirect_to(@user, notice: message)
      else
        render(action)
 end
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end


=begin
module UsersHelper

   def edit_user_link(user)
    link_to('Edit', edit_user_path(user))
  end
    def delete_user_link(user)
      link_to('Delete',user, method: :delete, data: {confirm: 'Are you sure you want to delete this?'})
  end

end
=end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ufind</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>All Finds </h1>
   <nav>

     <%= link_to("Create a Find!", new_user_path) %>
     <%= link_to("All Finds",users_path) %>

   <% if login_signed_in? %>
     Signed in as: <%= current_login.email %>
     <%= link_to("Log Out", destroy_login_session_path, method: :delete) %>
   <% else %>
      <%= link_to("Sign Up", new_login_registration_path) %>
      <%= link_to("Log In",  new_login_session_path) %>
   <% end %>
  </nav>

 <%if flash.notice %>
<div class="notice"> <%= flash.notice %> </div>
 <% end %>

 <%if flash.alert %>
<div class="alert"> <%= flash.alert %> </div>
 <% end %>
<%= yield %>


</body>


<h5> Copyright 2017 </h5>
</html>

app/views/users/_form.html.erb
 <% if @user.errors.any? %>

  <div class="errors1">
 <P> There were the following errors here </P>
  <ul>
    <%= @user.errors.full_messages.each do |error| %>
    <li> <%= error %> </li>
    <% end %>
  </ul>
 </div>
   <% end %>


<%= form_for(@user) do |f| %>
   <div>
    <%= f.label(:title) %>
    <%= f.text_field(:title,placeholder: "Enter text here") %>
    </div>
    <div>
      <%= f.label(:body) %>
      <%= f.text_area(:body,placeholder:"Enter body here") %>
      </div>
      <div>
        <%= f.submit %>
      </div>
      <% end %>

app/views/users/create.html.erb
<!--<p> <%= @user.id %> </p>
<p> <%= @user.created_at %> </p>
<p> <%= @user.title %> </p>
<p> <%= @user.body %> </p>-->
render 'form'

app/views/users/destroy.html.erb
<p> Your find has just been deleted. </p>

app/views/users/edit.html.erb
<h2>Edit find </h2>
<%= render("form")%>

app/views/users/index.html.erb
<h1> Welcome to Ufind, where we make things happen together! </h1>
<h2> Finds of The Day </h2>
<% if @users.any? %>
 <% @users.each do |user| %>
<div class="eachuser"> <h3><%= link_to(user.title, user_path(user)) %></h3>
    <p><%= user.body %> </p> </div>
  <% end %>
 <% else %>
   <p> There are no new find at this moment. </p>
  <% end %>

app/views/users/new.html.erb
<h1> New finds <h1>
<%= render("form") %>

app/views/users/show.html.erb
<p> <%= @user.title %></p>

<p> <%= @user.body %> </p>




 <p><%= link_to('Edit', edit_user_path(@user)) %> </p>
 <p><%= link_to('Delete',@user, method: :delete, data: {confirm: 'Are you sure you want to delete this?'})
%> <p>